### ISSUE TITLE
Can't initialize Application derivatives with specific size

### ISSUE THREAD

**Issue by VelocityRa** [JoshuaBrookover/bigg#12]
Either I'm missing something or (at least) [these two fields](https://github.com/JoshuaBrookover/bigg/blob/master/include/bigg.hpp#L91-L92) should be `protected`.

**Comment by widberg** [comment]
One possible solution would be to add the width and height as parameters in the [application constructor](https://github.com/JoshuaBrookover/bigg/blob/master/src/bigg.cpp#L193).

**Comment by JoshuaBrookover** [comment]
This code isn't really intended to be used without modification. It's more of an example than a framework, so it's missing a lot of little things that should be pretty easy to implement, like a "resize window" function. Pull requests always welcome. 😊

The PR #14 by @prowolf addresses this issue, so thanks for that!
