### ISSUE TITLE
OSX compilation error

### ISSUE THREAD

**Issue by dovodsc** [JoshuaBrookover/bigg#2]
bigg/deps/bgfx.cmake/bgfx/tools/texturev/texturev.cpp:6:10: fatal error: 
      'common.h' file not found

**Comment by jreach-dev** [comment]
Same on Windows.

I tried to solve it once but anything that includes common.h sucks in the entire bgfx example framework.

I may have solved it with my latest pull request. At least for Windows Visual Studio 2017.

What is texturev for?

**Comment by JoshuaBrookover** [comment]
texturev is a simple image viewing program. It is not necessary to build any of the other projects. This issue will be fixed when we update to newer bgfx.cmake.

**Comment by JoshuaBrookover** [comment]
Should be fixed now.
