### ISSUE TITLE
add_shader not working

### ISSUE THREAD

**Issue by gezilinll** [JoshuaBrookover/bigg#22]
Hello, examples/cubes will crash when it is running because shaders.bin not found, I run on osx

**Comment by gezilinll** [comment]
command: cmake -G Xcode ..

**Comment by widberg** [comment]
Are there any files in the build/examples/cubes/shaders/metal directory?

**Comment by gezilinll** [comment]
> Are there any files in the build/examples/cubes/shaders/metal directory?

Yes, the cubes demo is running successfully after I set working directory in Xcode scheme, but it's still crash if i use "cmake .. & make".
One more question, how can i generate all platform shaders, i didn't see essl result

**Comment by widberg** [comment]
add_shader is configured to build metal glsl essl asm.js spirv shaders on MacOS. Are any of those missing besides essl?

**Comment by gezilinll** [comment]
> add_shader is configured to build metal glsl essl asm.js spirv shaders on MacOS. Are any of those missing besides essl?

essl not found😄

**Comment by widberg** [comment]
I was unable to reproduce this issue using Xcode 10.3 and CMake 3.15.3 with the latest commit 2709802dc25ec1350e74c442337f846923100325. Please clone the bigg repository in a new location and build it from scratch to confirm that you are still experiencing this problem on the latest version.
