### ISSUE TITLE
Segmentation Fault with Windows 10 (MSYS2 MinGW 64-bit)

### ISSUE THREAD

**Issue by whabilly** [JoshuaBrookover/bigg#7]
I successfully built the project using "MSYS2 MinGW 64-bit" under Windows 10 (gcc 8.2.0, GNU make 4.2.1, make 3.12.2). However both the cubes and imgui demos trigger a segmentation fault as soon as the bgfx::init() call.
I also built and ran the original bgfx project using the same environment (mingw-gcc-release64) without any issue and all demos work just fine.
Any idea?

**Comment by JoshuaBrookover** [comment]
Not sure. I've slowly migrated away from Windows and haven't used MinGW in years. If bgfx::init segfaults then the init options being passed to it might be invalid. Maybe _WIN32 isn't defined? That would be pretty weird.

**Comment by whabilly** [comment]
Sorry, it looks like the issue was with the VM that was running Windows 10 (Parallels Desktop 14). I switched to BootCamp and now the project's demos run fine. Thanks!

**Comment by JoshuaBrookover** [comment]
Glad to hear it. 👍
